### ISSUE TITLE
literalinclude with linenos option doesn't show correct line numbers

### ISSUE THREAD

**Issue by humitos** [rtfd/sphinx_rtd_theme#415]
I'm moving an issue reported in RTD to here since it's more related with the theme than with RTD itself. See https://github.com/rtfd/readthedocs.org/issues/2783 for reference.

**Comment by Blendify** [comment]
This has been fixed in the next release you can try the beta now.

**Comment by humitos** [comment]
@rmk135 good news! can you test the beta version and confirm that it's fixed for your case?

**Comment by rmk135** [comment]
Hi guys,

I will try to test it.

**Comment by rmk135** [comment]
Ok, so I've just installed what you have in ``master`` branch, it's ``0.2.5b1``, and it works fine, problem is fixed.

Looking towards for 0.2.5 public release.

Thanks,
Roman

**Comment by Blendify** [comment]
Ok good to hear, closing.

**Comment by rmk135** [comment]
Hi all,

Was it ever releases on PyPi? I've just downloaded ``0.2.5b1`` from PyPI and it looks like that it does not contain this fix.

Do you have plans to release it?

Thanks,
Roman

**Comment by landam** [comment]
Unfortunately this bug is still present in building environment in http://readthedocs.io/. Is there any way how to fix it locally? Thanks.

**Comment by Blendify** [comment]
You will have to create a pip requirements file and that uses 0.2.5b1 as the version. You can then tell Read the Docs about this in the advanced project settings.

**Comment by landam** [comment]
Sounds easy, but somehow I got lost, no attempts were successful. I added requirements file (1), installed requirements locally and built HTML output (worked). But when I defined requirements.txt in RTD advanced settings or added YAML file, rebuilt, no success, see (2). Logs says:

```
 Requirement already satisfied: sphinx_rtd_theme==0.2.5b1 in /home/docs/checkouts/readthedocs.org/user_builds/gisquick/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 1)) 
```

Any idea what I am doing wrong? Thanks! 

(1) https://github.com/gislab-npo/gisquick-doc/blob/master/requirements.txt
(2) http://gisquick.readthedocs.io/en/latest/installation/docker.html

**Comment by Blendify** [comment]
Try disabling the option to give access to site-packages?

Aaron Carlisle

Picture taker | Bit cruncher | Pixel pusher | Document writer |
Project administrator for the Blender 3D Documentation Project

**Comment by Blendify** [comment]
As a better solution, I submitted a PR to update the theme version that RTD defaults to 0.2.5b1: https://github.com/rtfd/readthedocs.org/pull/3313

**Comment by landam** [comment]
Thanks, btw, probably it's time for releasing 0.2.5 (to avoid using betas)?

**Comment by landam** [comment]
By "Try disabling the option to give access to site-packages?" do you mean to turn on "Give the virtual environment access to the global site-packages dir." in advanced option? I tried that, but result is still the same. In the log there is still

```
 Requirement already satisfied: sphinx_rtd_theme==0.2.5b1 in /home/docs/checkouts/readthedocs.org/user_builds/gisquick/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 1)) 
```

but the HTML output is still broken.

**Comment by Blendify** [comment]
Not sure then I do not know the ins and outs of the RTD build process. So @ericholscher @agjohnson or @humitos will have to comment.

**Comment by vbotka** [comment]
+1
http://redis-py-examples.readthedocs.io/en/latest/examples.html#

**Comment by ltalirz** [comment]
I believe the relevant code is here

https://github.com/rtfd/readthedocs.org/blob/382c593f2630d235b020434e63d5f543a9059c10/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L41-L66

In short: RTD overwrites the theme, unless one provides an `html_style` in `conf.py` (see [html_style documentation](http://www.sphinx-doc.org/en/stable/config.html#confval-html_style))

Does anybody know what the right way would be to point `html_style` towards the user-installed `sphinx_rtd_theme`?

**Comment by vbotka** [comment]
My [conf.py](https://github.com/vbotka/redis-c-examples/blob/master/docs/source/conf.py) includes directives

> 
     html_theme = "sphinx_rtd_theme"
     html_theme_path = ['_themes', ]

and "sphinx_rtd_theme" 0.2.5b2 is available in the directory [_themes](https://github.com/vbotka/redis-c-examples/tree/master/docs/source/_themes)

It's working. I've tested. Switching to "guzzle_sphinx_theme" works fine. You might want to review this [conf.py](https://github.com/vbotka/redis-c-examples/blob/master/docs/source/conf.py)

The html_theme_path is not working on RTFD side.

**Comment by Blendify** [comment]
Hi all, we are really trying to get the next version released soon. Sorry
for the delay!

**Comment by vbotka** [comment]
For the record. The use of "html_style" instead of "html_theme" does not work.

>
     html_style = "sphinx_rtd_theme"
     html_static_path = ["_themes", ]
