### ISSUE TITLE
Sphinx deprecation warning

### ISSUE THREAD

**Issue by PhilippSelenium** [rtfd/sphinx_rtd_theme#739]
### Problem

sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead

### Reproducible Project

Sphinx: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/html.py#L108
RDT: https://github.com/rtfd/sphinx_rtd_theme/blob/b82993dfdb5559b40a0ab4839015bc6c093b6ddf/sphinx_rtd_theme/search.html#L20

```rst
Place RST code here (if any).
```

#### Expected Results

No deprecation warning

### Environment Info

- Python Version: Python 3.6.7
- Sphinx Version: Sphinx==2.0.0
- RTD Theme Version: sphinx-rtd-theme==0.4.3

**Comment by mik-laj** [comment]
Fix is available: https://github.com/rtfd/sphinx_rtd_theme/pull/728

**Comment by Blendify** [comment]
Fixed

**Comment by peterjc** [comment]
This has been fixed with the merge of #728 (April 2019), but there has not been a release to PyPI since - currently at sphinx-rtd-theme 0.4.3 (Feb 2019) which has the ``RemovedInSphinx30Warning`` message.

This breaks trying to run ``sphinx-build -W ...`` to catch regressions in documentation, so a point release would be most welcome.

**Comment by alanbchristie** [comment]
Wow - yes - any chance someone can release a `0.4.4`? It has been 6 months now.

**Comment by jack1142** [comment]
Weird, it doesn't break with `sphinx-build -W ...` for me 🤔

**Comment by peterjc** [comment]
You're right about  ``sphinx-build -W ...`` not aborting due to  ``RemovedInSphinx30Warning`` (I had a another warning further up the log which I had overlooked), sorry.

So the warning does seem to be cosmetic only, and not in itself enough to justify a point release.

**Comment by alexsuter** [comment]
I would also appreciate to get a new release. Because I get a warning in my build and I would like to set the quality gate of my build to zero warnings.

**Comment by haschdl** [comment]
I just updated to Sphinx 2.2 and I was disappointed to get the same Warning, then happy to see it's been fixed, then back to disappointed to see no Pip release. Anyway to facilitate a new pip release?

**Comment by vaneseltine** [comment]
Frustrating. For now I'm pip installing direct from github, pegged to a recent commit. This can be done in a requirements file like so:

```
-e git+https://github.com/readthedocs/sphinx_rtd_theme.git@feb0beb44a444f875f3369a945e6055965ee993f#egg=sphinx_rtd_theme
```

**Comment by PhilippSelenium** [comment]
Come on guys I'm still stuck to sphinx 1.8.5 because of this.

**Comment by ssbarnea** [comment]
I guess we can rename it to dontreadthedocs based on the speed with which a new release is made. Please, relase it!

**Comment by epogrebnyak** [comment]
Why is this issue closed? Should be a milestone, and an open issue. Anything we can do, how I can help? 

I'm getting, as everyone above

```
writing additional pages...  searchd:\anaconda3\lib\site-packages\sphinx_rtd_theme\search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}
```

**Comment by vaneseltine** [comment]
> Why is this issue closed? Should be a milestone, and an open issue. Anything we can do, how I can help?
> 
> I'm getting, as everyone above
> 
> ```
> writing additional pages...  searchd:\anaconda3\lib\site-packages\sphinx_rtd_theme\search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
>   {{ super() }}
> ```

It is closed because it has been fixed. Are you using the latest commit to this repository?

**Comment by epogrebnyak** [comment]
```
pip install sphinx_rtd_theme
```

produces

```
d:\anaconda3\lib\site-packages\m2r.py:652: RemovedInSphinx30Warning: app.add_source_parser() does not support suffix argument. Use app.add_source_suffix() instead.
  app.add_source_parser('.md', M2RParser)
d:\anaconda3\lib\site-packages\sphinx_rtd_theme\search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}
```

I tried installing latest commit as 

```
pip install git+https://github.com/readthedocs/sphinx_rtd_theme.git@2b8717a3647cc650625c566259e00305f7fb60aa#egg=sphinx_rtd_theme
```

but the install fails as 

```
Building wheels for collected packages: sphinx-rtd-theme
  Building wheel for sphinx-rtd-theme (setup.py) ... error
  Complete output from command D:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\B7E3~1\\AppData\\Local\\Temp\\pip-req-build-_q4154wj\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\B7E3~1\AppData\Local\Temp\pip-wheel-dp5qvj90 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  error: [WinError 2] Не удается найти указанный файл

  ----------------------------------------
  Failed building wheel for sphinx-rtd-theme
  Running setup.py clean for sphinx-rtd-theme
Failed to build sphinx-rtd-theme
Installing collected packages: sphinx-rtd-theme
  Found existing installation: sphinx-rtd-theme 0.4.3
    Uninstalling sphinx-rtd-theme-0.4.3:
      Successfully uninstalled sphinx-rtd-theme-0.4.3
  Running setup.py install for sphinx-rtd-theme ... error
    Complete output from command D:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\B7E3~1\\AppData\\Local\\Temp\\pip-req-build-_q4154wj\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\B7E3~1\AppData\Local\Temp\pip-record-7tjgw7ji\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    error: [WinError 2] Не удается найти указанный файл

    ----------------------------------------
  Rolling back uninstall of sphinx-rtd-theme
  Moving to d:\anaconda3\lib\site-packages\sphinx_rtd_theme-0.4.3.dist-info\
   from d:\anaconda3\lib\site-packages\~phinx_rtd_theme-0.4.3.dist-info
  Moving to d:\anaconda3\lib\site-packages\sphinx_rtd_theme\
   from d:\anaconda3\lib\site-packages\~phinx_rtd_theme
Command "D:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\B7E3~1\\AppData\\Local\\Temp\\pip-req-build-_q4154wj\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\B7E3~1\AppData\Local\Temp\pip-record-7tjgw7ji\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\B7E3~1\AppData\Local\Temp\pip-req-build-_q4154wj\
```

Either I'm doing install from repo wrong, or there is some bug that prevents from installation and it could have been the reason the newer code is not released to pypi. @vaneseltine - maybe you have an advice?

**Comment by epogrebnyak** [comment]
``` [WinError 2] Не удается найти указанный файл``` is *cannot find specified file*.

**Comment by vaneseltine** [comment]
> I tried installing latest commit as
> 
> ```
> pip install git+https://github.com/readthedocs/sphinx_rtd_theme.git@2b8717a3647cc650625c566259e00305f7fb60aa#egg=sphinx_rtd_theme
> ```

Yes, this line isn't quite what you want. You didn't include `-e` to make it editable -- so pip tried to build the package rather than simply using the pre-built egg. Building sphinx_rtd_theme requires some number of things you don't have on your system.

To use the egg, make sure `-e` is there:
```
pip install -e git+{address}#egg={package_name}
```
So you should not have the same problem with:
```
pip install -e git+https://github.com/readthedocs/sphinx_rtd_theme.git@2b8717a3647cc650625c566259e00305f7fb60aa#egg=sphinx_rtd_theme
```

**Comment by epogrebnyak** [comment]
Thanks for pointing to the `-e` flag! Installs just right with it. (I uninstall the package, then install from repo.)

Strangely the `RemovedInSphinx30Warning` still persists. Is there a way to locate why that may be happening in my project? Maybe I should try raising an exception rather than warning and debug to what causes it? Or there is a way to increase verbosity of the warning?


```
λ sphinx-build -b html docs gh-pages -c .
Running Sphinx v2.2.1
d:\anaconda3\lib\site-packages\m2r.py:652: RemovedInSphinx30Warning: app.add_source_parser() does not support suffix argument. Use app.add_source_suffix() instead.
  app.add_source_parser('.md', M2RParser)
```

**Comment by vaneseltine** [comment]
> d:\anaconda3\lib\site-packages\m2r.py

That looks like a similar problem with the m2r package... https://github.com/miyakogi/m2r/issues/34

Good luck 😅

**Comment by epogrebnyak** [comment]
Right you are! ))) I was too attached to exception name, not a package
name!

пн, 11 нояб. 2019 г., 21:18 Matt VanEseltine <notifications@github.com>:

**Comment by meherett** [comment]
Fixed

`pip install -e git+https://github.com/readthedocs/sphinx_rtd_theme.git@feb0beb44a444f875f3369a945e6055965ee993f#egg=sphinx_rtd_theme`

**Comment by vaneseltine** [comment]
> Fixed
> 
> ```
> pip install -e git+https://github.com/readthedocs/sphinx_rtd_theme.git@feb0beb44a444f875f3369a945e6055965ee993f#egg=sphinx_rtd_theme
> ```
> 

It's been fixed in master for months; the issue has been the pypi version lagging.
